[package]
name = "serdecraft"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = "0.4.6"
num-traits = "0.2.19"
num_enum = "0.7.4"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tungstenite = "0.27.0"
websocket = "0.27.1"
