[package]
name = "serdecraft"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
tungstenite = "0.27.0"
websocket = "0.27.1"
