[package]
name = "serdecraft"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
serde = "1.0.219"
torrento = { version = "0.1.0", path = "../torrento" }
tungstenite = "0.27.0"
websocket = "0.27.1"

[dev-dependencies]
serde_bencode = "0.2.4"
