#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MinecraftBlock {
    Stone,
    Cobblestone,
    QuartzBlock,

    WhiteWool,
    LightGrayWool,
    GrayWool,
    BlackWool,
    BrownWool,
    RedWool,
    OrangeWool,
    YellowWool,
    LimeWool,
    GreenWool,
    CyanWool,
    LightBlueWool,
    BlueWool,
    PurpleWool,
    MagentaWool,
    PinkWool,

    WhiteTerracotta,
    LightGrayTerracotta,
    GrayTerracotta,
    BlackTerracotta,
    BrownTerracotta,
    RedTerracotta,
    OrangeTerracotta,
    YellowTerracotta,
    LimeTerracotta,
    GreenTerracotta,
    CyanTerracotta,
    LightBlueTerracotta,
    BlueTerracotta,
    PurpleTerracotta,
    MagentaTerracotta,
    PinkTerracotta,

    CherryPlanks,
    BambooPlanks,
    BirchPlanks,
    OakPlanks,
    JunglePlanks,
    AcaciaPlanks,
    SprucePlanks,
    DarkOakPlanks,
    CrimsonPlanks,
    WarpedPlanks,

    CoalBlock,
    RedstoneBlock,

    CherryLog,
    BambooLog,
    BirchLog,
    OakLog,
    JungleLog,
    AcaciaLog,
    SpruceLog,
    DarkOakLog,
    CrimsonLog,
    WarpedLog,

    DarkOakFence,
    CherryFence,
    CrimsonFence,
    WarpedFence,

    GoldBlock,
    IronBlock,
    LapisBlock,

    RawGoldBlock,
    RawIronBlock,

    NetherQuartzBlock,
    CrimsonNylium,
    WarpedNylium,
}

impl std::fmt::Display for MinecraftBlock {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let w = match self {
            MinecraftBlock::Stone => "minecraft:stone",
            MinecraftBlock::Cobblestone => "minecraft:cobblestone",
            MinecraftBlock::QuartzBlock => "minecraft:quartz_block",
            MinecraftBlock::WhiteWool => "minecraft:white_wool",
            MinecraftBlock::LightGrayWool => "minecraft:light_gray_wool",
            MinecraftBlock::GrayWool => "minecraft:gray_wool",
            MinecraftBlock::BlackWool => "minecraft:black_wool",
            MinecraftBlock::BrownWool => "minecraft:brown_wool",
            MinecraftBlock::RedWool => "minecraft:red_wool",
            MinecraftBlock::OrangeWool => "minecraft:orange_wool",
            MinecraftBlock::YellowWool => "minecraft:yellow_wool",
            MinecraftBlock::LimeWool => "minecraft:lime_wool",
            MinecraftBlock::GreenWool => "minecraft:green_wool",
            MinecraftBlock::CyanWool => "minecraft:cyan_wool",
            MinecraftBlock::LightBlueWool => "minecraft:light_blue_wool",
            MinecraftBlock::BlueWool => "minecraft:blue_wool",
            MinecraftBlock::PurpleWool => "minecraft:purple_wool",
            MinecraftBlock::MagentaWool => "minecraft:magenta_wool",
            MinecraftBlock::PinkWool => "minecraft:pink_wool",
            MinecraftBlock::WhiteTerracotta => "minecraft:white_glazed_terracotta",
            MinecraftBlock::LightGrayTerracotta => "minecraft:light_gray_glazed_terracotta",
            MinecraftBlock::GrayTerracotta => "minecraft:gray_glazed_terracotta",
            MinecraftBlock::BlackTerracotta => "minecraft:black_glazed_terracotta",
            MinecraftBlock::BrownTerracotta => "minecraft:brown_glazed_terracotta",
            MinecraftBlock::RedTerracotta => "minecraft:red_glazed_terracotta",
            MinecraftBlock::OrangeTerracotta => "minecraft:orange_glazed_terracotta",
            MinecraftBlock::YellowTerracotta => "minecraft:yellow_glazed_terracotta",
            MinecraftBlock::LimeTerracotta => "minecraft:lime_glazed_terracotta",
            MinecraftBlock::GreenTerracotta => "minecraft:green_glazed_terracotta",
            MinecraftBlock::CyanTerracotta => "minecraft:cyan_glazed_terracotta",
            MinecraftBlock::LightBlueTerracotta => "minecraft:light_blue_glazed_terracotta",
            MinecraftBlock::BlueTerracotta => "minecraft:blue_glazed_terracotta",
            MinecraftBlock::PurpleTerracotta => "minecraft:purple_glazed_terracotta",
            MinecraftBlock::MagentaTerracotta => "minecraft:magenta_glazed_terracotta",
            MinecraftBlock::PinkTerracotta => "minecraft:pink_glazed_terracotta",
            MinecraftBlock::CherryPlanks => "minecraft:cherry_planks",
            MinecraftBlock::BambooPlanks => "minecraft:bamboo_planks",
            MinecraftBlock::BirchPlanks => "minecraft:birch_planks",
            MinecraftBlock::OakPlanks => "minecraft:oak_planks",
            MinecraftBlock::JunglePlanks => "minecraft:jungle_planks",
            MinecraftBlock::AcaciaPlanks => "minecraft:acacia_planks",
            MinecraftBlock::SprucePlanks => "minecraft:spruce_planks",
            MinecraftBlock::DarkOakPlanks => "minecraft:dark_oak_planks",
            MinecraftBlock::CrimsonPlanks => "minecraft:crimson_planks",
            MinecraftBlock::WarpedPlanks => "minecraft:warped_planks",
            MinecraftBlock::CoalBlock => "minecraft:coal_block",
            MinecraftBlock::RedstoneBlock => "minecraft:redstone_block",
            MinecraftBlock::CherryLog => "minecraft:cherry_log",
            MinecraftBlock::BambooLog => "minecraft:bamboo_block",
            MinecraftBlock::BirchLog => "minecraft:birch_log",
            MinecraftBlock::OakLog => "minecraft:oak_log",
            MinecraftBlock::JungleLog => "minecraft:jungle_log",
            MinecraftBlock::AcaciaLog => "minecraft:acacia_log",
            MinecraftBlock::SpruceLog => "minecraft:spruce_log",
            MinecraftBlock::DarkOakLog => "minecraft:dark_oak_log",
            MinecraftBlock::CrimsonLog => "minecraft:crimson_stem",
            MinecraftBlock::WarpedLog => "minecraft:warped_stem",
            MinecraftBlock::DarkOakFence => "minecraft:dark_oak_fence",
            MinecraftBlock::CherryFence => "minecraft:cherry_fence",
            MinecraftBlock::CrimsonFence => "minecraft:crimson_fence",
            MinecraftBlock::WarpedFence => "minecraft:warped_fence",
            MinecraftBlock::GoldBlock => "minecraft:gold_block",
            MinecraftBlock::IronBlock => "minecraft:iron_block",
            MinecraftBlock::LapisBlock => "minecraft:lapis_block",
            MinecraftBlock::RawGoldBlock => "minecraft:raw_gold_block",
            MinecraftBlock::RawIronBlock => "minecraft:raw_iron_block",
            MinecraftBlock::NetherQuartzBlock => "minecraft:nether_quartz_block",
            MinecraftBlock::CrimsonNylium => "minecraft:crimson_nylium",
            MinecraftBlock::WarpedNylium => "minecraft:warped_nylium",
        };

        write!(f, "{w}")
    }
}
